### ISSUE TITLE
Inconsistent decoder behaviour

### ISSUE THREAD

**Issue by cal97g** [hjson/hjson-py#12]
I have found some inconsistent behaviour with objects. I believe this is an issue with decoder.py, I looked into it but couldn't make sense of it. (Document obscure param names & methods please?)

Valid:
```
{
  admin: {
    os: {
      get: [id, name, version, servers]
      put: [name, version, servers]
      post: true
      delete: true}
...
```

Valid:
```
{
  admin: {
    os: {
      get: [id name version servers]
      put: [name version servers]
      post: true
      delete: true}
...
```

Valid:
```
{
  admin: {
    os: {
      get: [
        id,
        name,
        version,
        servers
      ]
      put: [
        name,
        version,
        servers
      ]
      post: true
      delete: true
    }
...
```
Invalid:
```
{
  admin: {
    os: {
      get: [id name version servers]
      put: [name version servers]
      post: true
      delete: true
    }
...
```

**Comment by laktak** [comment]
I can't repro your tests as you only posted parts of them.

However it looks like you are trying to use multiple unquoted strings on one line. If you want multiple values on one line you need to use quotes. Otherwise put every value on its own line (but then omit the comma).

See http://hjson.org/syntax.html#quoteless-strings
