### ISSUE TITLE
HJSON cannot handle a backslash character

### ISSUE THREAD

**Issue by mattmc3** [hjson/hjson-py#15]
It's not possible to encode a string with a backslash with this HJSON parser.

```
# A single slash won't work - empty string
# OrderedDict([('test', '')])
hjson.loads('''{"test": "\"}''')

# An escaped slash won't either
# HjsonDecodeError: Unterminated string starting at: line 1 column 10 (char 9)
hjson.loads('''{"test": "\\"}''')
```

**Comment by blubberdiblub** [comment]
This is not an error.

In the first case the string you're actually passing to the HJSON parser looks like this:
`{"test": ""}`

The reason is that you've got another meta-level of parsing there when specifying string literals in Python - the Python parser needs escapes for special characters as well. The backslash just (unnecessarily) escapes the following double quote for Python.

In the second case it's similar. Triple-quoted strings in Python still parse special characters the same way and still need escape of special characters. Therefore the string you're actually passing to the HJSON parser is this:
`{"test": "\"}`
Which of course is invalid in HJSON as it's escaping the last double quote to put into the value but then it's missing the terminating double quote of the string.

What you actually want to do is one of these:

1. `result = hjson.loads('{"test": "\\\\"}')` (single-quoted or triple-single-quoted Python string makes no difference here)
2. `result = hjson.loads(r'{"test": "\\"}')` (note the r introducing a raw string)

Both produce the same expected result:
```
>>> print(result['test'])
\
```
